os:
  - linux
language: go
go: 1.8.3
sudo: false
before_install:
- wget http://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
- tar -zxvf zookeeper*tar.gz
- export NN_PORT=9000
- export HADOOP_NAMENODE="localhost:$NN_PORT"
- export HADOOP_DISTRO=cdh
- export HADOOP_HOME="$HOME/hadoop"
- sh vendor/github.com/colinmarc/hdfs/setup_test_env.sh
before_script:
- make
script: make VERBOSE=1 test test_functional vet
before_deploy: make release
cache:
  directories:
  - "$HADOOP_HOME"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bNI1zixTuod6PBhCQzeGvZYOODqlEq0iRepcV5M6avVRbYMhW5zX4zxCfP155LXB9rA+xPpP0DEMVTAw9Q0MMSvdKPaBjQNlMPn87vZw6N09UajPYX8YZoUvxZD5XMBVFLsswC4oDaCptD/g6ilMQBT8hySHO8SFYjNWAGq04xM=
  file: sequins-*.tar.gz
  file_glob: true
  on:
    repo: stripe/sequins
    tags: true
    all_branches: true
env:
  global:
    # Region
    - secure: "giM8b/a4JfCDh6cpUyKo1uNUlNXZ28/PN3fnIN28s2GGvuipRCv+8BiqyxG6ukwPyQluHNxpsRcLFeXG2noSelHXY4HwdYZY5bDZ2xiWHTudphQD7gnQMoa8jSOx/66rLjMmx5UmtzlYfmsY9Rw1SshORWlgBmMeIYNWYu1NJiw="
